Probability plot and table- Process capability Updates
jasp-stats/jaspProcessControl pull request #18
Opened 2020-11-18 14:53 UTC by tomishay

Updates:
- Lognormal distribution 
- Weibull distributon 
- Table

2020-11-19 08:55 UTC, koenderks commented
If you have a common function like `ProbabilityPlotNoId`, can you adjust it in the common file instead of adding it to the process capability analysis?

2020-11-19 10:43 UTC, tomishay commented
I just adjusted the Common R file and the rest of the sections so there is no overlap between the functions.

2020-11-19 15:31 UTC, koenderks commented
@tomishay It has nothing to do with your code

2020-11-20 10:06 UTC, vandenman requested changes
looks good! two small comments below

2020-11-20 10:06 UTC, vandenman commented on R/processCapability.R
> +      dataset.factors <- na.omit(.readDataSetToEnd(columns = variables, columns.as.factor = subgroupsName))
there's an argument for this already
```suggestion
      dataset         <- .readDataSetToEnd(columns.as.numeric = variables, columns.as.factor = subgroupsName, exclude.na.listwise = c(variables, subgroupsName))
      dataset.factors <- .readDataSetToEnd(columns = variables, columns.as.factor = subgroupsName, exclude.na.listwise = c(variables, subgroupsName))
```

2020-11-20 10:06 UTC, vandenman commented on inst/qml/processCapability.qml
> +  VariablesForm
please indent qml with tabs, not spaces.

2020-11-23 13:39 UTC, merged