Control charts- update and addition.
jasp-stats/jaspProcessControl pull request #48
Opened 2021-01-20 14:41 UTC by tomishay

- Updated limits and warning signals for the X and R charts.
- Addition of attribute charts: P, NP, C, and U.

2021-01-21 14:53 UTC, koenderks requested changes
The contents of your commonRfile.R are now supposed to be in the commonQualityControl.R file. Can you please rebase first and make sure this is the case?

2021-01-29 10:21 UTC, tomishay commented
Yes that is indeed the case

2021-01-29 15:09 UTC, koenderks requested changes
I have added some suggestions for improvement, after that I think this can be merged.

2021-01-29 15:09 UTC, koenderks commented on R/controlCharts.R
> +  data1 <- data.frame(D = dataset[, encodeColNames(options$D)], sample = dataset[, encodeColNames(options$total)])
No need for `encodeColNames()`

2021-01-29 15:09 UTC, koenderks commented on R/controlCharts.R
> +  data1 <- data.frame(D = dataset[, encodeColNames(options$D)], sample = dataset[, encodeColNames(options$total)])
See above

2021-01-29 15:09 UTC, koenderks commented on R/controlCharts.R
> +  xBreaks <- jaspGraphs::getPrettyAxisBreaks(c(subgroups))
No need to use `c()`

2021-01-29 15:09 UTC, koenderks commented on R/controlCharts.R
> +  ready <- options$D > 0 & options$total > 0
See above

2021-01-29 15:09 UTC, koenderks commented on R/controlCharts.R
> +  data1 <- data.frame(D = dataset[, encodeColNames(options$D)], sample = dataset[, encodeColNames(options$total)])
Same here

2021-01-29 15:09 UTC, koenderks commented on R/controlCharts.R
> +  ready <- options$D > 0 & options$total > 0
Here also

2021-01-29 15:09 UTC, koenderks commented on R/controlCharts.R
> +  data1 <- data.frame(D = dataset[, encodeColNames(options$D)], sample = dataset[, encodeColNames(options$total)])
No `encodeColNames()`

2021-01-29 15:09 UTC, koenderks commented on R/processCapability.R
> +# This program is free software: you can redistribute it and/or modify
Can you delete this file?

2021-01-29 15:09 UTC, koenderks commented on R/processControl.R
> +# Copyright (C) 2013-2018 University of Amsterdam
Can you also delete this file?

2021-01-29 15:09 UTC, koenderks commented on inst/qml/controlCharts.qml
> +        CheckBox {	name: "ImRchart";		label: qsTr("I-mR chart for variables")				}
Maybe just I-mR charts? Because it is under the variables header anywari

2021-01-29 15:09 UTC, koenderks commented on inst/qml/controlCharts.qml
> +            CheckBox {	name: "ImRchart2";		label: qsTr("I-mR chart for attributes")												}
Same suggestion as above

2021-01-29 15:09 UTC, koenderks commented on inst/qml/processCapability.qml
> +// it under the terms of the GNU Affero General Public License as
Can you delete this file?

2021-02-10 12:13 UTC, koenderks requested changes
A couple of suggestions ordered from most to least important:
- In several plots you specify `xLimits <- range(xBreaks + 3)` but I that causes the x-axis to not start at 0 since you not only add 3 to the maximum but also to the minimum. The plot below shows this and you can see that the x-axis starts at Subgroup 3. Shouldn't this be starting at subgroup 1? Because now you actually do not show the first two subgroups from the data in the figure.
![image](https://user-images.githubusercontent.com/25059399/107505868-980da280-6b9d-11eb-8538-e6e06bbacaf8.png)
Maybe you can specify this as `xLimits <- c(1, max(xBreaks) + 4)`? You will then also have to change `x = max(xLimits)` to `x = max(xLimits - 1)` in the `dfLabel` data frame. You will also have to change you x-axes arguments, so for example `ggplot2::scale_x_continuous(name = 'Observations', breaks = xBreaks, limits = c(min(xLimits), max(xLimits) + 1))` becomes `ggplot2::scale_x_continuous(name = 'Observations', breaks = xBreaks, limits = range(xLimits))`. Doing that makes the x-axis start at 1 and still shows the numbers on the right. The figure below shows how it will look with these changes. This should be changed in all the plots!
![image](https://user-images.githubusercontent.com/25059399/107507401-cd1af480-6b9f-11eb-8ee8-fabcad509c04.png)
- Don't forget to add `gettext()` to all the strings that the user will see, so for example the axes names in `ggplot2::scale_x_continuous(name = 'Subgroups', breaks = xBreaks, limits = c(min(xLimits), max(xLimits) + 1))`.
- You specify the `position` of each plot as 11 every time, but this just causes the plots to appear in the order that the user requests them. If you want that, then it is best practice to not assign a `position` to the plot at all. If you want them to appear in a specific order, please adjust the `position` of the plots.
- Please add a `.` before the `controlCharts` function name to be consistent with the rest of JASP. So `controlCharts` becomes `.controlCharts`. 

Can you change these things and push these changes?

2021-02-10 13:47 UTC, tomishay commented
Thanks for the feedback @koenderks! I changed everything, the only thing is that when I change the analysis's name to `.controlCharts` the analysis doesn't work. I guess because I need to change the name somewhere else too. Do you know how can I fix this?

2021-02-10 13:49 UTC, koenderks commented
Oh my bad Tom, I see that I have been a sloppy reviewer. I did not realize that that function was the actual analysis. No, you can leave it that way then! Can you push the changes you made? Then I'll take another look!

2021-02-10 15:44 UTC, koenderks approved these changes
I think we are good to go! Even though the x-axis still starts at zero (not sure how the code is different though...), that is something that we can always fix later.

2021-02-10 15:46 UTC, merged